debian/tmp/usr/lib/*/wineVERSION/bin/wmc
debian/tmp/usr/lib/*/wineVERSION/bin/wrc
debian/tmp/usr/lib/*/wineVERSION/bin/widl
debian/tmp/usr/lib/*/wineVERSION/bin/winecpp
debian/tmp/usr/lib/*/wineVERSION/bin/winegcc
debian/tmp/usr/lib/*/wineVERSION/bin/wineg++
debian/tmp/usr/lib/*/wineVERSION/bin/winedump
debian/tmp/usr/lib/*/wineVERSION/bin/winebuild
debian/tmp/usr/lib/*/wineVERSION/bin/winemaker

debian/tmp/usr/lib/*/wineVERSION/bin/function_grep.pl

debian/tmp/winegccDEBSUFFIX usr/bin
