@ stdcall CreateDXGIFactory(ptr ptr)
@ stdcall CreateDXGIFactory1(ptr ptr)
@ stdcall CreateDXGIFactory2(long ptr ptr)
@ stdcall D3DKMTCloseAdapter(ptr) gdi32.D3DKMTCloseAdapter
@ stdcall D3DKMTCreateAllocation(ptr) gdi32.D3DKMTCreateAllocation
@ stdcall D3DKMTCreateContext(ptr) gdi32.D3DKMTCreateContext
@ stdcall D3DKMTCreateDevice(ptr) gdi32.D3DKMTCreateDevice
@ stdcall D3DKMTCreateSynchronizationObject(ptr) gdi32.D3DKMTCreateSynchronizationObject
@ stdcall D3DKMTDestroyAllocation(ptr) gdi32.D3DKMTDestroyAllocation
@ stdcall D3DKMTDestroyContext(ptr) gdi32.D3DKMTDestroyContext
@ stdcall D3DKMTDestroyDevice(ptr) gdi32.D3DKMTDestroyDevice
@ stdcall D3DKMTDestroySynchronizationObject(ptr) gdi32.D3DKMTDestroySynchronizationObject
@ stdcall D3DKMTEscape(ptr) gdi32.D3DKMTEscape
@ stdcall D3DKMTGetContextSchedulingPriority(ptr) gdi32.D3DKMTGetContextSchedulingPriority
@ stdcall D3DKMTGetDeviceState(ptr) gdi32.D3DKMTGetDeviceState
@ stdcall D3DKMTGetDisplayModeList(ptr) gdi32.D3DKMTGetDisplayModeList
@ stdcall D3DKMTGetMultisampleMethodList(ptr) gdi32.D3DKMTGetMultisampleMethodList
@ stdcall D3DKMTGetRuntimeData(ptr) gdi32.D3DKMTGetRuntimeData
@ stdcall D3DKMTGetSharedPrimaryHandle(ptr) gdi32.D3DKMTGetSharedPrimaryHandle
@ stdcall D3DKMTLock(ptr) gdi32.D3DKMTLock
@ stdcall D3DKMTOpenAdapterFromHdc(ptr) gdi32.D3DKMTOpenAdapterFromHdc
@ stdcall D3DKMTOpenResource(ptr) gdi32.D3DKMTOpenResource
@ stdcall D3DKMTPresent(ptr) gdi32.D3DKMTPresent
@ stdcall D3DKMTQueryAdapterInfo(ptr) gdi32.D3DKMTQueryAdapterInfo
@ stdcall D3DKMTQueryAllocationResidency(ptr) gdi32.D3DKMTQueryAllocationResidency
@ stdcall D3DKMTQueryResourceInfo(ptr) gdi32.D3DKMTQueryResourceInfo
@ stdcall D3DKMTRender(ptr) gdi32.D3DKMTRender
@ stdcall D3DKMTSetAllocationPriority(ptr) gdi32.D3DKMTSetAllocationPriority
@ stdcall D3DKMTSetContextSchedulingPriority(ptr) gdi32.D3DKMTSetContextSchedulingPriority
@ stdcall D3DKMTSetDisplayMode(ptr) gdi32.D3DKMTSetDisplayMode
@ stdcall D3DKMTSetDisplayPrivateDriverFormat(ptr) gdi32.D3DKMTSetDisplayPrivateDriverFormat
@ stdcall D3DKMTSetGammaRamp(ptr) gdi32.D3DKMTSetGammaRamp
@ stdcall D3DKMTSetVidPnSourceOwner(ptr) gdi32.D3DKMTSetVidPnSourceOwner
@ stdcall D3DKMTSignalSynchronizationObject(ptr) gdi32.D3DKMTSignalSynchronizationObject
@ stdcall D3DKMTUnlock(ptr) gdi32.D3DKMTUnlock
@ stdcall D3DKMTWaitForSynchronizationObject(ptr) gdi32.D3DKMTWaitForSynchronizationObject
@ stdcall D3DKMTWaitForVerticalBlankEvent(ptr) gdi32.D3DKMTWaitForVerticalBlankEvent
@ stdcall DXGID3D10CreateDevice(ptr ptr ptr long ptr long ptr)
@ stdcall DXGID3D10RegisterLayers(ptr long)
@ stdcall DXGIGetDebugInterface1(long ptr ptr)
